org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora
java_version=25

# Mod properties
mod_version=1.3.1
mod_name=Lovely Snails
mod_namespace=lovely_snails
modrinth_id=hBVVhStr
curseforge_id=499425

fabric.loom.dropNonIntermediateRootMethods=true
